export const OPEN_ACCOUNT_SUCCESS = 'OPEN_ACCOUNT_SUCCESS';
export const OPEN_ACCOUNT_FAILURE = 'OPEN_ACCOUNT_FAILURE';
export const VALIDATE_ACCOUNT_SUCCESS = 'VALIDATE_ACCOUNT_SUCCESS';
export const VALIDATE_ACCOUNT_FAILURE = 'VALIDATE_ACCOUNT_FAILURE';
